name: Build & Publish Weekly

on:
  schedule:
    - cron: "0 7 * * 1"   # Lundi 07:00 UTC (~09:00 Paris été, ~08:00 hiver)
  workflow_dispatch: {}    # garde le bouton “Run workflow”

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 'npm ci' peut échouer sans package-lock.json → fallback sur 'npm i'
      - run: npm ci || npm i

      # Génère le site (dossier public/)
      - run: node generate-weekly.js

      # Prépare GitHub Pages et upload l'artefact
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
